# Generated by Django 4.2.23 on 2025-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_alter_link_target_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="is_tracked",
            field=models.BooleanField(
                default=True,
                help_text="Should clicking this url create a `LinkVisit` object?",
            ),
        ),
    ]
