# Generated by Django 4.2.23 on 2025-08-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_link_is_tracked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="is_tracked",
            field=models.BooleanField(
                default=False,
                help_text="Should clicking this url create a `LinkVisit` object?",
            ),
        ),
    ]
