services:
  app:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./backups:/var/backups
      - static-clubs-prod:/vol/web
    environment:
      - PORT=9000
      - WORKER_COUNT=${WORKER_COUNT:-6}
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
    env_file:
      - .env
    networks:
      - cluster
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 60s
      start_interval: 15s
    depends_on:
      - redis
      - pgbouncer

  app_replica:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - static-clubs-prod:/vol/web
    environment:
      - PORT=9000
      - WORKER_COUNT=${WORKER_COUNT:-6}
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
    env_file:
      - .env
    networks:
      - cluster
    depends_on:
      # Wait until app is ready, in case app needs to run migrations
      app:
        condition: service_healthy
    deploy:
      mode: replicated
      endpoint_mode: vip
      replicas: ${APP_REPLICAS:-3}

  redis:
    image: redis:8.6-alpine
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis8-clubs-prod:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "ping"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 10s
    networks:
      - cluster
    configs:
      - source: redis.conf
        target: /usr/local/etc/redis/redis.conf
    sysctls:
      # Accept up to 65535 connections in the listen backlog
      - net.core.somaxconn=65535

  celery:
    build:
      context: .
    restart: unless-stopped
    user: django-user
    command: ["celery", "-A", "app", "worker", "--loglevel=info"]
    volumes:
      - ./app:/app/app
      - static-clubs-prod:/vol/web
    depends_on:
      redis:
        condition: service_started
      app:
        condition: service_healthy
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
      - REDIS_HOST=redis:6379
    env_file:
      - .env
    networks:
      - cluster

  celerybeat:
    build:
      context: .
    user: django-user
    restart: unless-stopped
    command:
      [
        "celery",
        "-A",
        "app",
        "beat",
        "--loglevel=info",
        "--scheduler",
        "django_celery_beat.schedulers:DatabaseScheduler",
      ]
    volumes:
      - ./app:/app/app
      - static-clubs-prod:/vol/web
    depends_on:
      redis:
        condition: service_started
      app:
        condition: service_healthy
      celery:
        condition: service_started
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
      - REDIS_HOST=redis:6379
    env_file:
      - .env
    networks:
      - cluster

  proxy:
    build:
      context: ./deploy/proxy/
    restart: unless-stopped
    container_name: clubs-prod-proxy
    ports:
      - 8080:8080
    depends_on:
      # Wait until app is ready, in case app needs to run migrations
      app:
        condition: service_healthy
    volumes:
      - static-clubs-prod:/vol/web
    environment:
      - PORT=8080
      - SERVER_URI=app:9000
      - SERVER_REPLICA_URI=app_replica:9000
      - PROXY_DOCS_URI=${PROXY_DOCS_URI:-''}
      - S3_STORAGE_BUCKET_NAME=${S3_STORAGE_BUCKET_NAME}
      - ENV=PROD
      # No delay needed, since app has health checks
      - DELAY=0s
    networks:
      - cluster
    sysctls:
      # Accept up to 65535 connections in the listen backlog
      - net.core.somaxconn=65535

  postgres:
    image: postgres:17.7-alpine
    volumes:
      - postgres-clubs-prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - cluster
    configs:
      - source: postgresql.auto.conf
        target: /var/lib/postgresql/postgresql.auto.conf
    sysctls:
      # Accept up to 65535 connections in the listen backlog
      - net.core.somaxconn=65535

  pgbouncer:
    image: edoburu/pgbouncer
    restart: always
    depends_on:
      - postgres
    networks:
      - cluster
    configs:
      - source: pgbouncer.ini
        target: /etc/pgbouncer/pgbouncer.ini
      - source: userlist.txt
        target: /etc/pgbouncer/userlist.txt
    sysctls:
      # Accept up to 65535 connections in the listen backlog
      - net.core.somaxconn=65535

volumes:
  static-clubs-prod:
  redis8-clubs-prod:
    name: "redis8-clubs-prod"

  postgres-clubs-prod:
    name: "postgres17-clubs-prod"

configs:
  # Postgres Config Settings
  # Use .auto.conf instead of .conf so default conf is not altered
  postgresql.auto.conf:
    # Docs: https://www.postgresql.org/docs/15/runtime-config.html
    content: |
      max_connections = 1000

  # PGBouncer Config Settings
  pgbouncer.ini:
    # Docs: https://www.pgbouncer.org/config.html
    content: |
      [databases]
      * = host=postgres port=5432 auth_user=${POSTGRES_USER} dbname=${POSTGRES_NAME}
      ${POSTGRES_NAME} = host=postgres port=5432 auth_user=${POSTGRES_USER}

      [pgbouncer]
      listen_addr = pgbouncer
      listen_port = 6432
      auth_type = plain
      auth_file = /etc/pgbouncer/userlist.txt
      pool_mode = transaction
      max_client_conn = 1000
      default_pool_size = 100

      log_connections = 0
      log_disconnections = 0
      stats_period = 300

      admin_users = ${POSTGRES_USER}
  userlist.txt:
    content: |
      "${POSTGRES_USER}" "${POSTGRES_PASSWORD}"

  # Redis Settings
  redis.conf:
    # Ref: https://oneuptime.com/blog/post/2026-01-21-redis-docker-compose/view#production-ready-docker-compose
    content: |
      # Network
      bind 0.0.0.0
      port 6379
      protected-mode yes
      tcp-backlog 511

      # Security
      requirepass ${REDIS_PASSWORD:-changeme}

      # Memory
      maxmemory 450mb
      maxmemory-policy allkeys-lru
      maxmemory-samples 5

      # Persistence
      appendonly yes
      appendfsync everysec
      no-appendfsync-on-rewrite no
      auto-aof-rewrite-percentage 100
      auto-aof-rewrite-min-size 64mb

      save 900 1
      save 300 10
      save 60 10000

      # Performance
      tcp-keepalive 300
      timeout 0

      # Lazy freeing
      lazyfree-lazy-eviction yes
      lazyfree-lazy-expire yes
      lazyfree-lazy-server-del yes

      # Logging
      loglevel notice
      logfile ""

networks:
  cluster:
    name: club_portal_prod
    driver: bridge
