"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
import sys
from pathlib import Path
from socket import gethostbyname, gethostname

import sentry_sdk  # type: ignore
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def environ_bool(key: str, default=0):
    return bool(int(os.environ.get(key, default)))


def environ_list(key: str, default=""):
    return [item.strip() for item in filter(None, os.environ.get(key, default).split(","))]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-changeme")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environ_bool("DJANGO_DEBUG", 0)
"""Debug mode implements better logging."""

DEV = os.environ.get("DEV", None) == "true"
"""Dev mode installs additional development packages."""

TESTING = sys.argv[1:2] == ["test"]

ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(environ_list("DJANGO_ALLOWED_HOSTS"))
ALLOWED_HOSTS.extend([os.environ.get("DJANGO_BASE_URL")])

BASE_URL = os.environ.get("DJANGO_BASE_URL", "")
ALLOWED_HOSTS.extend([BASE_URL])
CLIENT_URL = os.environ.get("CLIENT_URL", "http://localhost:5173")
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

EVENT_ATTENDANCE_REDIRECT_URL = os.environ.get(
    "EVENT_ATTENDANCE_REDIRECT_URL", CLIENT_URL + "/events/%(id)s"
)
"""Where should user go when attending event? Supports formatting variable `%(id)s`."""

POLL_SUBMISSION_REDIRECT_URL = os.environ.get(
    "POLL_SUBMISSION_REDIRECT_URL", CLIENT_URL + "/forms/%(id)s"
)
"""Where should user go when submitting polls? Supports formatting variable `%(id)s`."""

DJANGO_ENABLE_API_SESSION_AUTH = False

SCHOOL_EMAIL_DOMAIN = "ufl.edu"

ASGI_APPLICATION = "app.asgi.application"

# Application definition

INSTALLED_APPS = [
    "django_celery_beat",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "drf_standardized_errors",
    "django_filters",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.headless",
    "core",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "users.authentication",
    "querycsv",
    "analytics",
    "clubs",
    "events",
    "polls",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware", # TODO: Enable CSRF, implement with frontend
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django.middleware.locale.LocaleMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "core.middleware.TimezoneMiddleware",
]


ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "core/templates"),
            os.path.join(BASE_DIR, "dashboard/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            # "loaders": [
            #     "django.template.loaders.filesystem.Loader",
            #     "django.template.loaders.app_directories.Loader",
            #     "admin_tools.template_loaders.Loader",
            # ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
        "NAME": os.environ.get("POSTGRES_NAME"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "DISABLE_SERVER_SIDE_CURSORS": True,  # Fixes "InvalidCursorName" issues in prod
        "CONN_MAX_AGE": 0,
        "OPTIONS": {
            "pool": {
                "min_size": 1,
                "max_size": int(os.environ.get("POSTGRES_MAX_POOL_SIZE", 1)),
                "timeout": 60,
            }
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "America/New_York" # TODO: UTC
TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_URL = "/static/static/"
MEDIA_URL = "/static/media/"

MEDIA_ROOT = "/vol/web/media"
STATIC_ROOT = "/vol/web/static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Rest Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_standardized_errors.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Club Portal API",
    "DESCRIPTION": "Some cool app to manage users or something.",
    "VERSION": "1.0.0",
    "SCHEMA_PATH_PREFIX": "/api/v1/",
    "ENUM_NAME_OVERRIDES": {
        "ValidationErrorEnum": "drf_standardized_errors.openapi_serializers.ValidationErrorEnum.choices",
        "ClientErrorEnum": "drf_standardized_errors.openapi_serializers.ClientErrorEnum.choices",
        "ServerErrorEnum": "drf_standardized_errors.openapi_serializers.ServerErrorEnum.choices",
        "ErrorCode401Enum": "drf_standardized_errors.openapi_serializers.ErrorCode401Enum.choices",
        "ErrorCode403Enum": "drf_standardized_errors.openapi_serializers.ErrorCode403Enum.choices",
        "ErrorCode404Enum": "drf_standardized_errors.openapi_serializers.ErrorCode404Enum.choices",
        "ErrorCode405Enum": "drf_standardized_errors.openapi_serializers.ErrorCode405Enum.choices",
        "ErrorCode406Enum": "drf_standardized_errors.openapi_serializers.ErrorCode406Enum.choices",
        "ErrorCode415Enum": "drf_standardized_errors.openapi_serializers.ErrorCode415Enum.choices",
        "ErrorCode429Enum": "drf_standardized_errors.openapi_serializers.ErrorCode429Enum.choices",
        "ErrorCode500Enum": "drf_standardized_errors.openapi_serializers.ErrorCode500Enum.choices",
    },
    "POSTPROCESSING_HOOKS": ["drf_standardized_errors.openapi_hooks.postprocess_schema_enums"],
}
DRF_STANDARDIZED_ERRORS = {"ENABLE_IN_DEBUG_FOR_UNHANDLED_EXCEPTIONS": True}

FIXTURE_DIRS = [os.path.join(BASE_DIR, "fixtures")]


###############################
# == Auth & Session Config == #
###############################

# Allows handling csrf and session cookies in external requests
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

# Prevent csrf and session cookies from being set by JS
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = False

# Only allow cookies from these origins
CSRF_TRUSTED_ORIGINS = environ_list("CSRF_TRUSTED_ORIGINS")

# Only allow cookies to be sent over HTTPS
CSRF_COOKIE_SECURE = environ_bool("CSRF_COOKIE_SECURE", False)
SESSION_COOKIE_SECURE = environ_bool("SESSION_COOKIE_SECURE", False)

# CORS Settings
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]
CORS_ALLOW_CREDENTIALS = True

# Other auth settings
AUTH_USER_MODEL = "users.User"
LOGIN_REDIRECT_URL = "/admin/"
LOGIN_URL = "/admin/login/"
AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
    "core.backend.CustomBackend",
]

# Used for logging in a user via api
DEFAULT_AUTH_BACKEND = "core.backend.CustomBackend"

# OAuth Settings
# Docs: https://docs.allauth.org/en/latest/
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", None),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", None),
        },
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
    "github": {
        "SCOPE": ["user:email"],
        "APP": {
            "client_id": os.environ.get("GITHUB_CLIENT_ID", None),
            "secret": os.environ.get("GITHUB_CLIENT_SECRET", None),
        },
    },
}

SOCIALACCOUNT_QUERY_EMAIL = True
HEADLESS_SERVE_SPECIFICATION = True

# Enable to force email verification
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = "mandatory"

HEADLESS_ADAPTER = "lib.allauth.CustomHeadlessAdapter"
ACCOUNT_ADAPTER = "lib.allauth.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "lib.allauth.CustomSocialAccountAdapter"


############################
# ==  Production Config == #
############################
# AWS S3
S3_STORAGE_BACKEND = bool(int(os.environ.get("S3_STORAGE_BACKEND", 1)))
if S3_STORAGE_BACKEND is True and TESTING is False:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_DEFAULT_ACL = "public-read"
AWS_STORAGE_BUCKET_NAME = os.environ.get("S3_STORAGE_BUCKET_NAME", "")
AWS_S3_REGION_NAME = os.environ.get("S3_STORAGE_BUCKET_REGION", "us-east-1")
AWS_QUERYSTRING_AUTH = False

AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")

# Sentry
sentry_sdk.init(dsn=os.environ.get("SENTRY_DSN", ""), send_default_pii=True, traces_sample_rate=1.0)


######################
# == Email Config == #
######################
CONSOLE_EMAIL_BACKEND = environ_bool("DJANGO_CONSOLE_EMAIL_BACKEND", 0)
SMTP_EMAIL_BACKEND = environ_bool("DJANGO_SMTP_EMAIL_BACKEND", 0)

if CONSOLE_EMAIL_BACKEND:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", None)

# EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "smtp.sendgrid.net")
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "apikey")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", SENDGRID_API_KEY)
EMAIL_PORT = os.environ.get("DJANGO_EMAIL_PORT", 587)
EMAIL_USE_TLS = environ_bool("DJANGO_EMAIL_USE_TLS", 1)
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "admin@example.com")

#######################
# == Celery Config == #
#######################
DJANGO_ENABLE_CELERY = environ_bool("DJANGO_ENABLE_CELERY", 1)
"""When disabled, runs as a single server."""

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")
CELERY_TASK_ACKS_LATE = bool(int(os.environ.get("CELERY_TASK_ACKS_LATE", "1")))
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = bool(
    int(os.environ.get("CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP", "1"))
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Custom schedules
CELERY_BEAT_SCHEDULE = {}
CELERY_BEAT_ENABLE_HEARTBEAT = environ_bool("CELERY_BEAT_ENABLE_HEARTBEAT", 0)

if CELERY_BEAT_ENABLE_HEARTBEAT:
    CELERY_BEAT_SCHEDULE["heartbeat"] = {
        "task": "core.tasks.heartbeat_task",
        "schedule": crontab(minute="*"),
    }

DJANGO_REDIS_URL = os.environ.get("DJANGO_REDIS_URL", None)

if DJANGO_REDIS_URL is not None:
    # assert (
    #     DEV is True or DEBUG is True
    # ), "Django needs a redis server in production mode."

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.environ.get("DJANGO_REDIS_URL"),
        }
    }


###############################
# == Environment Overrides == #
###############################

if environ_bool("AWS_EXECUTION_ENV", 1):
    ALLOWED_HOSTS.append(gethostbyname(gethostname()))

if DEV:
    import socket

    # INSTALLED_APPS.append("debug_toolbar")
    INSTALLED_APPS.append("django_browser_reload")
    INSTALLED_APPS.append("django_extensions")

    # Insert near top, adjust pos as needed
    # MIDDLEWARE.insert(3, "debug_toolbar.middleware.DebugToolbarMiddleware")
    # DJANGO_ALLOW_ASYNC_UNSAFE = True  # Allows django debug toolbar to work
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")
    CSRF_TRUSTED_ORIGINS.extend(["http://0.0.0.0", "http://localhost", "http://127.0.0.1"])
    CORS_ORIGIN_ALLOW_ALL = True

    INTERNAL_IPS = ["127.0.0.1", "10.0.2.2", "localhost"]
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "level": "DEBUG",
            },
        },
        "loggers": {
            "django.request": {
                "handlers": ["console"],  # Use the handler configured for DEBUG
                "level": "DEBUG",
                "propagate": False,  # Prevents messages from being passed to parent loggers
            },
        },
    }

if DEV and not TESTING:

    # Ref: https://stackoverflow.com/a/64726422/10914922
    def show_toolbar(*args, **kwargs):
        return not TESTING and environ_bool("DJANGO_SHOW_TOOLBAR", 1)

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": show_toolbar,
        "IS_RUNNING_TESTS": False,
    }


if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(["http://0.0.0.0"])
    logging.disable(logging.NOTSET)

    DJANGO_ENABLE_API_SESSION_AUTH = environ_bool("DJANGO_ENABLE_DEV_API_SESSION_AUTH", 1)


if TESTING:
    # Ensure tasks execute immediately
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_ALWAYS_EAGER = True

    S3_STORAGE_BACKEND = False
    AWS_STORAGE_BUCKET_NAME = ""

    # Force disable notifications
    EMAIL_HOST_PASSWORD = None
    # Suppress logs in test mode
    logging.disable(logging.ERROR)

    # Force disconnect from social providers
    for provider in SOCIALACCOUNT_PROVIDERS.keys():
        SOCIALACCOUNT_PROVIDERS[provider]["APP"] = {
            "client_id": f"test-{provider}-id",
            "secret": f"test-{provider}-secret",
        }


if DEV or TESTING:
    # Allow for migrations during dev mode
    INSTALLED_APPS.append("core.mock")

    # Disable caching
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
