"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
import sys
from pathlib import Path
from socket import gethostbyname, gethostname

import sentry_sdk  # type: ignore
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def environ_bool(key: str, default=0):
    return bool(int(os.environ.get(key, default)))


def environ_list(key: str, default=""):
    return [
        item.strip() for item in filter(None, os.environ.get(key, default).split(","))
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-changeme")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environ_bool("DJANGO_DEBUG", 0)
"""Debug mode implements better logging."""

DEV = os.environ.get("DEV", None) == "true"
"""Dev mode installs additional development packages."""

TESTING = sys.argv[1:2] == ["test"]

ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(environ_list("DJANGO_ALLOWED_HOSTS"))
ALLOWED_HOSTS.extend([os.environ.get("DJANGO_BASE_URL")])
ALLOWED_HOSTS.append(gethostbyname(gethostname()))  # Allow access via ip address

BASE_URL = os.environ.get("DJANGO_BASE_URL", "")
ALLOWED_HOSTS.extend([BASE_URL])
CLIENT_URL = os.environ.get("CLIENT_URL", "http://localhost:5173")
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

EVENT_ATTENDANCE_REDIRECT_URL = os.environ.get(
    "EVENT_ATTENDANCE_REDIRECT_URL", CLIENT_URL + "/events/%(id)s"
)
"""Where should user go when attending event? Supports formatting variable `%(id)s`."""

POLL_SUBMISSION_REDIRECT_URL = os.environ.get(
    "POLL_SUBMISSION_REDIRECT_URL", CLIENT_URL + "/forms/%(id)s"
)
"""Where should user go when submitting polls? Supports formatting variable `%(id)s`."""

DJANGO_ENABLE_API_SESSION_AUTH = False

SCHOOL_EMAIL_DOMAIN = "ufl.edu"

ASGI_APPLICATION = "app.asgi.application"


# Application definition

INSTALLED_APPS = [
    "storages",
    "django_celery_beat",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "drf_standardized_errors",
    "django_filters",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.headless",
    "core",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "users",
    "users.authentication",
    "querycsv",
    "analytics",
    "clubs",
    "events",
    "polls",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",  # TODO: Enable CSRF, implement with frontend
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django.middleware.locale.LocaleMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "core.middleware.TimezoneMiddleware",
]


ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "core/templates"),
            os.path.join(BASE_DIR, "dashboard/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            # "loaders": [
            #     "django.template.loaders.filesystem.Loader",
            #     "django.template.loaders.app_directories.Loader",
            #     "admin_tools.template_loaders.Loader",
            # ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

POSTGRES_MAX_POOL_SIZE = int(os.environ.get("POSTGRES_MAX_POOL_SIZE", "0"))
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
        "NAME": os.environ.get("POSTGRES_NAME"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "DISABLE_SERVER_SIDE_CURSORS": True,  # Fixes "InvalidCursorName" issues in prod
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {},
    }
}

if POSTGRES_MAX_POOL_SIZE > 0:
    DATABASES["default"]["OPTIONS"]["pool"] = {
        "min_size": 1,
        "max_size": POSTGRES_MAX_POOL_SIZE,
        "timeout": 60,
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "America/New_York" # TODO: UTC
TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Rest Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_standardized_errors.openapi.AutoSchema",
    # "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    "EXCEPTION_HANDLER": "core.views.api_exception_handler",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Club Portal API",
    "DESCRIPTION": "Some cool app to manage users or something.",
    "VERSION": "1.0.0",
    "SCHEMA_PATH_PREFIX": "/api/v1/",
    "ENUM_NAME_OVERRIDES": {
        "ValidationErrorEnum": "drf_standardized_errors.openapi_serializers.ValidationErrorEnum.choices",
        "ClientErrorEnum": "drf_standardized_errors.openapi_serializers.ClientErrorEnum.choices",
        "ServerErrorEnum": "drf_standardized_errors.openapi_serializers.ServerErrorEnum.choices",
        "ErrorCode401Enum": "drf_standardized_errors.openapi_serializers.ErrorCode401Enum.choices",
        "ErrorCode403Enum": "drf_standardized_errors.openapi_serializers.ErrorCode403Enum.choices",
        "ErrorCode404Enum": "drf_standardized_errors.openapi_serializers.ErrorCode404Enum.choices",
        "ErrorCode405Enum": "drf_standardized_errors.openapi_serializers.ErrorCode405Enum.choices",
        "ErrorCode406Enum": "drf_standardized_errors.openapi_serializers.ErrorCode406Enum.choices",
        "ErrorCode415Enum": "drf_standardized_errors.openapi_serializers.ErrorCode415Enum.choices",
        "ErrorCode429Enum": "drf_standardized_errors.openapi_serializers.ErrorCode429Enum.choices",
        "ErrorCode500Enum": "drf_standardized_errors.openapi_serializers.ErrorCode500Enum.choices",
    },
    "POSTPROCESSING_HOOKS": [
        "drf_standardized_errors.openapi_hooks.postprocess_schema_enums"
    ],
}
DRF_STANDARDIZED_ERRORS = {"ENABLE_IN_DEBUG_FOR_UNHANDLED_EXCEPTIONS": True}

FIXTURE_DIRS = [os.path.join(BASE_DIR, "fixtures")]


###############################
# == Auth & Session Config == #
###############################

# Allows handling csrf and session cookies in external requests
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

# Prevent csrf and session cookies from being set by JS
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = False

# Only allow cookies from these origins
CSRF_TRUSTED_ORIGINS = environ_list("CSRF_TRUSTED_ORIGINS")

# Only allow cookies to be sent over HTTPS
CSRF_COOKIE_SECURE = environ_bool("CSRF_COOKIE_SECURE", False)
SESSION_COOKIE_SECURE = environ_bool("SESSION_COOKIE_SECURE", False)

# CORS Settings
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]
CORS_ALLOW_CREDENTIALS = True

# Other auth settings
AUTH_USER_MODEL = "users.User"
LOGIN_REDIRECT_URL = "/admin/"
LOGIN_URL = "/admin/login/"
AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
    "core.backend.CustomBackend",
]

# Used for logging in a user via api
DEFAULT_AUTH_BACKEND = "core.backend.CustomBackend"

# OAuth Settings
# Docs: https://docs.allauth.org/en/latest/
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", None),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", None),
        },
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
    "github": {
        "SCOPE": ["user:email"],
        "APP": {
            "client_id": os.environ.get("GITHUB_CLIENT_ID", None),
            "secret": os.environ.get("GITHUB_CLIENT_SECRET", None),
        },
    },
}

SOCIALACCOUNT_QUERY_EMAIL = True
HEADLESS_SERVE_SPECIFICATION = True

# Enable to force email verification
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = "mandatory"

HEADLESS_ADAPTER = "lib.allauth.CustomHeadlessAdapter"
ACCOUNT_ADAPTER = "lib.allauth.CustomAccountAdapter"
SOCIALACCOUNT_ADAPTER = "lib.allauth.CustomSocialAccountAdapter"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

##########################################
# == Static Files Config =============== #
##########################################
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
S3_STORAGE_BACKEND = environ_bool("S3_STORAGE_BACKEND", 1) and not TESTING
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# URL path to file
STATIC_URL = "/files/static/"
MEDIA_URL = "/files/media/public/"

# Physical location in file system
MEDIA_ROOT = "/vol/web/media/public"
STATIC_ROOT = "/vol/web/static"

# Media and static storage config
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {},
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        "OPTIONS": {},
    },
}

if S3_STORAGE_BACKEND:
    MEDIA_ROOT = None  # This is ignored by boto3, but still included for clarity

    AWS_STORAGE_BUCKET_NAME = os.environ.get("S3_STORAGE_BUCKET_NAME", "")
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
    AWS_S3_REGION_NAME = os.environ.get("S3_STORAGE_BUCKET_REGION", "us-east-1")

    # Split base url to provide to boto3 backend
    # TODO: Figure out why proxy no longer works with s3
    # protocol, domain = BASE_URL.split("//")
    # AWS_S3_CUSTOM_DOMAIN = domain + "/files/media"
    # AWS_S3_URL_PROTOCOL = protocol

    # When enabled, set the default storage to use AWS S3
    STORAGES["default"] = {
        "BACKEND": "core.storage.PublicMediaStorage",
    }


# Sentry
sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", ""), send_default_pii=True, traces_sample_rate=1.0
)


######################
# == Email Config == #
######################
CONSOLE_EMAIL_BACKEND = environ_bool("DJANGO_CONSOLE_EMAIL_BACKEND", 0)
SMTP_EMAIL_BACKEND = environ_bool("DJANGO_SMTP_EMAIL_BACKEND", 0)

if CONSOLE_EMAIL_BACKEND:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY", None)

EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "smtp.sendgrid.net")
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "apikey")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", SENDGRID_API_KEY)
EMAIL_PORT = os.environ.get("DJANGO_EMAIL_PORT", 587)
EMAIL_USE_TLS = environ_bool("DJANGO_EMAIL_USE_TLS", 1)
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "admin@example.com")

#######################
# == Cache Config === #
#######################

REDIS_HOST = os.environ.get("REDIS_HOST")
DJANGO_CACHE_REDIS_DB = os.environ.get("DJANGO_CACHE_REDIS_DB", 0)

DJANGO_REDIS_URL = f"redis://{REDIS_HOST}/{DJANGO_CACHE_REDIS_DB}"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": DJANGO_REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

#######################
# == Celery Config == #
#######################
DJANGO_ENABLE_CELERY = environ_bool("DJANGO_ENABLE_CELERY", 1)
"""When disabled, runs as a single server."""

# What celery uses to communicate to workers
CELERY_BROKER_REDIS_DB = os.environ.get("CELERY_BROKER_REDIS_DB", 1)
CELERY_BROKER_URL = f"redis://{REDIS_HOST}/{CELERY_BROKER_REDIS_DB}"

# What celery uses to store results of tasks
CELERY_RESULT_BACKEND_REDIS_DB = os.environ.get("CELERY_RESULT_BROKER_REDIS_DB", 1)
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}/{CELERY_RESULT_BACKEND_REDIS_DB}"

CELERY_TASK_ACKS_LATE = bool(int(os.environ.get("CELERY_TASK_ACKS_LATE", "1")))
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = bool(
    int(os.environ.get("CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP", "1"))
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Custom schedules
CELERY_BEAT_SCHEDULE = {}
CELERY_BEAT_ENABLE_HEARTBEAT = environ_bool("CELERY_BEAT_ENABLE_HEARTBEAT", 0)

if CELERY_BEAT_ENABLE_HEARTBEAT:
    CELERY_BEAT_SCHEDULE["heartbeat"] = {
        "task": "core.tasks.heartbeat_task",
        "schedule": crontab(minute="*"),
    }

#########################
# == Channels Config == #
#########################
CHANNELS_REDIS_DB = os.environ.get("CHANNELS_REDIS_DB", 2)
CHANNELS_REDIS_URL = f"redis://{REDIS_HOST}/{CHANNELS_REDIS_DB}"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNELS_REDIS_URL],
        },
    },
}


###############################
# == Environment Overrides == #
###############################

if DEV:
    import socket

    INSTALLED_APPS.append("debug_toolbar")
    # INSTALLED_APPS.append("django_browser_reload")
    INSTALLED_APPS.append("django_extensions")

    # Insert near top, adjust pos as needed
    MIDDLEWARE.insert(3, "debug_toolbar.middleware.DebugToolbarMiddleware")
    # MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")
    CSRF_TRUSTED_ORIGINS.extend(
        ["http://0.0.0.0", "http://localhost", "http://127.0.0.1"]
    )
    CORS_ORIGIN_ALLOW_ALL = True
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"  # Set allauth to use http instead of https

    INTERNAL_IPS = ["127.0.0.1", "10.0.2.2", "localhost"]
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]


if DEV and not TESTING:
    # Ref: https://stackoverflow.com/a/64726422/10914922
    def show_toolbar(*args, **kwargs):
        return not TESTING and environ_bool("DJANGO_SHOW_TOOLBAR", 1)

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": show_toolbar,
        "IS_RUNNING_TESTS": False,
    }


if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(["http://0.0.0.0"])
    logging.disable(logging.NOTSET)

    DJANGO_ENABLE_API_SESSION_AUTH = environ_bool(
        "DJANGO_ENABLE_DEV_API_SESSION_AUTH", 1
    )


if DEV or DEBUG:
    POSTGRES_ECHO = environ_bool("POSTGRES_ECHO", 0)

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "level": "DEBUG",
            },
        },
        "loggers": {
            "django.request": {
                "handlers": ["console"],  # Use the handler configured for DEBUG
                "level": "DEBUG",
                "propagate": False,  # Prevents messages from being passed to parent loggers
            },
        },
    }

    if POSTGRES_ECHO:
        LOGGING["loggers"]["django.db.backends"] = {
            "handlers": [
                "console",
            ],
            "level": "DEBUG",
            "propagate": False,
        }


if TESTING:
    # Ensure tasks execute immediately
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_ALWAYS_EAGER = True

    S3_STORAGE_BACKEND = False
    AWS_STORAGE_BUCKET_NAME = ""

    # Force disable notifications
    EMAIL_HOST_PASSWORD = None
    # Suppress logs in test mode
    logging.disable(logging.ERROR)

    # Force disconnect from social providers
    for provider in SOCIALACCOUNT_PROVIDERS.keys():
        SOCIALACCOUNT_PROVIDERS[provider]["APP"] = {
            "client_id": f"test-{provider}-id",
            "secret": f"test-{provider}-secret",
        }


if DEV or TESTING:
    # Allow for migrations during dev mode
    INSTALLED_APPS.append("core.mock")
