# Generated by Django 4.2.20 on 2025-03-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0026_alter_club_options_and_more"),
        ("users", "0009_socialprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clubs",
            field=models.ManyToManyField(
                blank=True, through="clubs.ClubMembership", to="clubs.club"
            ),
        ),
    ]
