# Generated by Django 4.2.20 on 2025-03-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_clubs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprofile",
            name="username",
            field=models.CharField(blank=True, null=True),
        ),
    ]
