# Generated by Django 4.2.20 on 2025-03-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_socialprofile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(
                blank=True, help_text="Mr/Mrs/Dr/etc", max_length=255, null=True
            ),
        ),
    ]
