# Generated by Django 4.2.20 on 2025-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_rename_title_profile_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
