# Generated by Django 4.2.20 on 2025-04-10 17:23

from django.db import migrations


def migrate_set_user_display(apps, schema_editor):
    """Iterate over all users and save them - triggering the display auto population."""

    User = apps.get_model("users", "User")

    for user in User.objects.all():
        if getattr(user, "profile", None) is None:
            continue

        profile = user.profile
        if profile.display is None or profile.display.strip() == "":
            name = f"{profile.prefix or ''} {profile.first_name or ''} {profile.last_name or ''}".strip()
            if name != "":
                profile.display = name
            else:
                profile.display = user.email.split("@")[0]
        profile.save()


def migrate_reverse_set_user_display(apps, schema_editor):
    """Iterate over all users and remove display field."""

    User = apps.get_model("users", "User")

    for user in User.objects.all():
        user.display_name = None


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_profile_display"),
    ]

    operations = [
        migrations.RunPython(migrate_set_user_display, migrate_reverse_set_user_display)
    ]
