# Generated by Django 4.2.20 on 2025-04-12 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_manual_set_display"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAgent",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("users.user",),
        ),
        migrations.AlterField(
            model_name="profile",
            name="display",
            field=models.CharField(
                blank=True,
                help_text="Name to use when displaying the user.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
