# Generated by Django 4.2.20 on 2025-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_useragent_alter_profile_display_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useragent",
            name="apikey_type",
            field=models.CharField(choices=[("club", "Club")], null=True),
        ),
    ]
