# Generated by Django 4.2.20 on 2025-04-13 15:57

from django.db import migrations


def migrate_set_default_apikey_type(apps, schema_editor):
    """For each user agent, set default key type."""

    UserAgent = apps.get_model("users", "UserAgent")

    for user in UserAgent.objects.all():
        user.apikey_type = "club"
        user.save()


def migrate_reverse_set_defalt_apikey_type(apps, schema_editor):
    """For each user agent, unset default key type."""

    UserAgent = apps.get_model("users", "UserAgent")

    for user in UserAgent.objects.all():
        user.apikey_type = None
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_useragent_apikey_type"),
    ]

    operations = [
        migrations.RunPython(
            migrate_set_default_apikey_type, migrate_reverse_set_defalt_apikey_type
        )
    ]
