# Generated by Django 4.2.20 on 2025-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_manual_apikey_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useragent",
            name="apikey_type",
            field=models.CharField(choices=[("club", "Club Api Key")]),
        ),
    ]
