# Generated by Django 4.2.23 on 2025-06-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_useragent_apikey_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
