# Generated by Django 4.2.23 on 2025-06-17 22:57

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_user_is_onboarded_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.models.UploadFilepathFactory("users/profiles/"),
            ),
        ),
    ]
