# Generated by Django 4.2.23 on 2025-06-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
