# Generated by Django 4.2.23 on 2025-06-21 23:04

from django.db import migrations


def migrate_set_user_name(apps, schema_editor):
    """For each user, set their name field using individual name fields."""

    Profile = apps.get_model("users", "Profile")

    for profile in Profile.objects.all():
        if profile.first_name or profile.last_name:
            profile.name = f"{profile.prefix or ''} {profile.first_name or ''} {profile.last_name or ''}".strip()
            profile.save()


def migrate_reverse_set_user_name(apps, schema_editor):
    """For each user, unset their name field."""

    Profile = apps.get_model("users", "Profile")

    for profile in Profile.objects.all():
        profile.name = None
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_profile_name"),
    ]

    operations = [
        migrations.RunPython(migrate_set_user_name, migrate_reverse_set_user_name),
    ]
