# Generated by Django 4.2.23 on 2025-06-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_manual_set_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="display",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="nickname",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="prefix",
        ),
    ]
