# Generated by Django 4.2.23 on 2025-06-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
