# Generated by Django 4.2.23 on 2025-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_remove_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprofile",
            name="social_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("discord", "Discord"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter (X)"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("website", "Personal Website"),
                    ("bluesky", "BlueSky"),
                    ("other", "Other"),
                ],
            ),
        ),
    ]
