# Generated by Django 4.2.23 on 2025-09-03 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_socialprofile_social_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
