# Generated by Django 4.2.23 on 2025-08-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_socialprofile_social_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="college",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="minor",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
