# Generated by Django 4.2.23 on 2025-08-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_profile_college_profile_minor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="graduation_year",
        ),
        migrations.AddField(
            model_name="profile",
            name="graduation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
