# Generated by Django 4.2.23 on 2025-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_remove_profile_graduation_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cached_email",
            field=models.EmailField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
