# Generated by Django 4.2.23 on 2025-08-24 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_user_cached_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="graduation_date",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\d{4}-\\d{2}", message="Invalid format, try YYYY-MM"
                    )
                ],
            ),
        ),
    ]
