# Generated by Django 4.2.23 on 2025-09-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_populate_calendar_tokens"),
        ("users", "0036_alter_profile_graduation_date"),
    ]

    operations = []
