# Generated by Django 4.2.24 on 2025-09-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0054_clubfile_origin"),
        ("users", "0036_alter_profile_graduation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teams",
            field=models.ManyToManyField(
                blank=True, through="clubs.TeamMembership", to="clubs.team"
            ),
        ),
    ]
