# Generated by Django 5.2.8 on 2025-11-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cached_email",
            field=models.EmailField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
