# Generated by Django 5.2.8 on 2026-02-02 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_user_cached_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="used_at",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(), blank=True, editable=False, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="emailverificationcode",
            name="uses",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
