# Generated by Django 4.2.23 on 2026-02-04

import uuid
from django.db import migrations, models


def generate_calendar_tokens(apps, schema_editor):
    """Generate unique calendar tokens for all existing users."""
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.calendar_token = uuid.uuid4()
        user.save(update_fields=['calendar_token'])


def reverse_calendar_tokens(apps, schema_editor):
    """Reverse migration - set all calendar_tokens to NULL."""
    User = apps.get_model("users", "User")
    User.objects.update(calendar_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_emailverificationcode_used_at_and_more"),
    ]

    operations = [
        # Add field without unique constraint first
        migrations.AddField(
            model_name="user",
            name="calendar_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Populate unique tokens for existing users
        migrations.RunPython(
            generate_calendar_tokens,
            reverse_calendar_tokens,
        ),
        # Now add the unique constraint
        migrations.AlterField(
            model_name="user",
            name="calendar_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
