# Generated by Django 5.2.8 on 2026-02-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_emailverificationcode_used_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailverificationcode",
            name="used_at",
        ),
        migrations.RemoveField(
            model_name="emailverificationcode",
            name="uses",
        ),
    ]
