# Generated by Django 5.2.8 on 2026-02-16 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_remove_emailverificationcode_used_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
