# Generated by Django 5.2.8 on 2026-02-21 18:04

import uuid

from django.db import migrations


def migrate_populate_user_calendar_token(apps, schema_editor):
    """For each user, generate unique calendar token."""
    
    User = apps.get_model('users', 'User')
    
    for user in User.objects.all():
        user.calendar_token = uuid.uuid4()
        user.save()
    
def migrate_reverse_populate_user_calendar_token(apps, schema_editor):
    """Clear out all calendar tokens."""
    
    User = apps.get_model('users', 'User')
    
    for user in User.objects.all():
        user.calendar_token = None
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_user_calendar_token"),
    ]

    operations = [
        migrations.RunPython(migrate_populate_user_calendar_token, migrate_reverse_populate_user_calendar_token)
    ]
