# Generated by Django 5.2.8 on 2026-02-21 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_manual_populate_calendar_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="calendar_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
