# Generated by Django 4.2.20 on 2025-03-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustertag",
            name="color",
            field=models.CharField(blank=True, null=True),
        ),
    ]
