# Generated by Django 4.2.20 on 2025-03-20 20:38

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("mock", "0002_bustertag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="buster",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.models.UploadFilepathFactory("buster/images/"),
            ),
        ),
    ]
