# Generated by Django 4.2.20 on 2025-06-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock", "0003_buster_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="buster",
            name="unique_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
