# Generated by Django 4.2.20 on 2025-06-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("querycsv", "0002_alter_querycsvuploadjob_serializer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="querycsvuploadjob",
            options={"verbose_name": "CSV Upload"},
        ),
        migrations.AddField(
            model_name="querycsvuploadjob",
            name="error",
            field=models.CharField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="querycsvuploadjob",
            name="failed_count",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="querycsvuploadjob",
            name="success_count",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="querycsvuploadjob",
            name="report",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to="core/querycsv/reports/",
            ),
        ),
    ]
