# Generated by Django 4.2.23 on 2025-06-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("querycsv", "0003_alter_querycsvuploadjob_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="querycsvuploadjob",
            name="ended_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="querycsvuploadjob",
            name="logs",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="querycsvuploadjob",
            name="started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="querycsvuploadjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                    ("contains_errors", "Contains Errors"),
                ],
                default="pending",
            ),
        ),
    ]
