# Generated by Django 4.2.23 on 2025-06-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("querycsv", "0004_querycsvuploadjob_ended_at_querycsvuploadjob_logs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querycsvuploadjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                    ("contains_errors", "Contains Errors"),
                    ("invalid", "Invalid CSV"),
                ],
                default="pending",
            ),
        ),
    ]
