# Generated by Django 4.2.23 on 2025-06-27 20:48

import django.core.validators
from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("querycsv", "0005_alter_querycsvuploadjob_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querycsvuploadjob",
            name="file",
            field=models.FileField(
                upload_to=utils.models.UploadFilepathFactory(
                    default_extension="csv", path="core/querycsv/uploads/"
                ),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("csv", "xls", "xlsx", "json")
                    )
                ],
            ),
        ),
    ]
