# Generated by Django 4.2.20 on 2025-03-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0022_clubmembership_one_membership_per_user_and_club"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventattendance",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventattendance",
            name="member",
        ),
        migrations.RemoveField(
            model_name="eventattendancelink",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventattendancelink",
            name="link_ptr",
        ),
        migrations.RemoveField(
            model_name="recurringevent",
            name="club",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventAttendance",
        ),
        migrations.DeleteModel(
            name="EventAttendanceLink",
        ),
        migrations.DeleteModel(
            name="EventTag",
        ),
        migrations.DeleteModel(
            name="RecurringEvent",
        ),
    ]
