# Generated by Django 4.2.20 on 2025-03-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0023_remove_eventattendance_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubsocialprofile",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
