# Generated by Django 4.2.20 on 2025-03-20 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0024_alter_clubsocialprofile_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubtag",
            name="name",
            field=models.CharField(
                max_length=32, validators=[django.core.validators.MinLengthValidator(2)]
            ),
        ),
    ]
