# Generated by Django 4.2.20 on 2025-03-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0025_alter_clubtag_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["name", "-id"],
                "permissions": [
                    ("preview_club", "Can view a set of limited fields for a club.")
                ],
            },
        ),
        migrations.AlterField(
            model_name="clubsocialprofile",
            name="social_type",
            field=models.CharField(
                choices=[
                    ("discord", "Discord"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter (X)"),
                    ("linkedin", "LinkedIn"),
                ]
            ),
        ),
    ]
