# Generated by Django 4.2.20 on 2025-03-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0026_alter_club_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubsocialprofile",
            name="username",
            field=models.CharField(blank=True, null=True),
        ),
    ]
