# Generated by Django 4.2.20 on 2025-04-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clubs", "0027_alter_clubsocialprofile_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                (
                    "default",
                    models.BooleanField(
                        default=False,
                        help_text="New members would be automatically assigned this role.",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="clubs.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teammembership",
            name="roles",
            field=models.ManyToManyField(blank=True, to="clubs.teamrole"),
        ),
        migrations.AddConstraint(
            model_name="teamrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default", True)),
                fields=("default", "team"),
                name="only_one_default_team_role_per_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamrole",
            constraint=models.UniqueConstraint(
                fields=("name", "team"), name="unique_rolename_per_team"
            ),
        ),
    ]
