# Generated by Django 4.2.20 on 2025-04-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0028_teamrole_teammembership_roles_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clubmembership",
            name="only_one_owner_per_club",
        ),
        migrations.RenameField(
            model_name="clubmembership",
            old_name="owner",
            new_name="is_owner",
        ),
        migrations.AddConstraint(
            model_name="clubmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_owner", True)),
                fields=("club", "is_owner"),
                name="only_one_owner_per_club",
            ),
        ),
    ]
