# Generated by Django 4.2.20 on 2025-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0029_remove_clubmembership_only_one_owner_per_club_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubsocialprofile",
            name="social_type",
            field=models.CharField(
                choices=[
                    ("discord", "Discord"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter (X)"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("website", "Personal Website"),
                    ("bluesky", "BlueSky"),
                    ("other", "Other"),
                ]
            ),
        ),
    ]
