# Generated by Django 4.2.20 on 2025-04-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_useragent_alter_profile_display_alter_user_email_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clubs", "0030_alter_clubsocialprofile_social_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clubs.club"
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Allowed permissions for this club only.",
                        to="auth.permission",
                    ),
                ),
                (
                    "user_agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.useragent",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="clubapikey",
            constraint=models.UniqueConstraint(
                fields=("name", "club"), name="unique_apikey_name_per_club"
            ),
        ),
    ]
