# Generated by Django 4.2.20 on 2025-04-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_useragent_apikey_type"),
        ("clubs", "0031_clubapikey_clubapikey_unique_apikey_name_per_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubapikey",
            name="user_agent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="club_apikey",
                to="users.useragent",
            ),
        ),
    ]
