# Generated by Django 4.2.20 on 2025-05-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0032_alter_clubapikey_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="is_admin",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
