# Generated by Django 4.2.23 on 2025-07-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_remove_user_is_onboarded"),
        ("clubs", "0034_club_banner_clubphoto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubapikey",
            options={"verbose_name": "Api Key"},
        ),
        migrations.AlterField(
            model_name="clubapikey",
            name="user_agent",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="club_apikey",
                to="users.useragent",
            ),
        ),
    ]
