# Generated by Django 4.2.23 on 2025-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0034_club_banner_clubphoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="color",
            field=models.CharField(default="0F44CD", max_length=6),
        ),
    ]
