# Generated by Django 4.2.23 on 2025-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0035_club_acronym_club_category_ids_club_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.TextField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="clubsocialprofile",
            name="social_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("discord", "Discord"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter (X)"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("website", "Personal Website"),
                    ("bluesky", "BlueSky"),
                    ("other", "Other"),
                ],
            ),
        ),
    ]
