# Generated by Django 4.2.23 on 2025-07-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0035_alter_clubapikey_options_alter_clubapikey_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembership",
            name="order_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teamrole",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Used to determine the list ordering of a team member",
            ),
        ),
    ]
