# Generated by Django 4.2.23 on 2025-07-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0036_alter_club_name_alter_clubsocialprofile_social_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="alias",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
