# Generated by Django 4.2.23 on 2025-07-06 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0036_teammembership_order_override_teamrole_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubsocialprofile",
            options={},
        ),
        migrations.AddField(
            model_name="club",
            name="gatorconnect_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^https:\\/\\/orgs\\.studentinvolvement\\.ufl\\.edu\\/Organization\\/"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clubsocialprofile",
            name="social_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("discord", "Discord"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter (X)"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("website", "Personal Website"),
                    ("bluesky", "BlueSky"),
                    ("slack", "Slack"),
                    ("other", "Other"),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="clubsocialprofile",
            constraint=models.UniqueConstraint(
                fields=("club", "social_type", "url"),
                name="unique_social_urls_per_club",
            ),
        ),
    ]
