# Generated by Django 4.2.23 on 2025-07-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0038_clubfile_delete_clubphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="clubs.club",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clubs.clubfile"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="clubphoto",
            constraint=models.UniqueConstraint(
                fields=("order", "club"), name="unique_order_per_club"
            ),
        ),
    ]
