# Generated by Django 4.2.23 on 2025-07-09 03:26

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0039_clubphoto_clubphoto_unique_order_per_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubfile",
            name="file",
            field=models.FileField(
                upload_to=utils.models.UploadNestedClubFilepathFactory(
                    "clubs/%(club_id)s/files/"
                )
            ),
        ),
    ]
