# Generated by Django 4.2.23 on 2025-07-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_alter_clubfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='color',
            field=models.CharField(default='0F44CD', max_length=6),
        ),
    ]
