# Generated by Django 4.2.23 on 2025-07-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0040_alter_clubfile_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="club",
            name="logo",
        ),
    ]
