# Generated by Django 4.2.23 on 2025-07-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0041_club_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clubs.clubfile'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clubs.clubfile'),
        ),
    ]
