# Generated by Django 4.2.23 on 2025-07-20 20:55

from django.db import migrations

from utils.files import get_file_from_path
from utils.images import create_default_icon


def migrate_set_club_logo(apps, schema_editor):
    """Set default club logo for all clubs without a logo."""

    Club = apps.get_model("clubs", "Club")
    ClubFile = apps.get_model("clubs", "ClubFile")

    for club in Club.objects.filter(logo__isnull=True):
        initials = club.alias or club.name[0]
        logo_path = create_default_icon(
            initials, image_path="clubs/images/generated/", fileprefix=club.pk
        )
        logo = ClubFile.objects.create(club=club, file=get_file_from_path(logo_path))

        club.logo = logo
        club.save()


def migrate_reverse_set_club_logo(apps, schema_editor):
    """Remove all auto generated club logos from clubs."""

    Club = apps.get_model("clubs", "Club")
    ClubFile = apps.get_model("clubs", "ClubFile")

    for club in Club.objects.filter(logo__uploaded_by__isnull=True, logo__isnull=False):

        ClubFile.objects.filter(id=club.logo.id).delete()
        # club.logo.delete()
        # club.logo = None

        # club.save()


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0043_alter_clubfile_uploaded_by"),
    ]

    operations = [
        migrations.RunPython(migrate_set_club_logo, migrate_reverse_set_club_logo)
    ]
