# Generated by Django 4.2.23 on 2025-07-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0044_set_default_clublogo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubmembership",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="clubrole",
            name="role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("custom", "Custom"),
                ],
                default="viewer",
            ),
        ),
        migrations.AddField(
            model_name="teamrole",
            name="role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("custom", "Custom"),
                ],
                default="viewer",
            ),
        ),
        migrations.AlterField(
            model_name="clubmembership",
            name="is_owner",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Determines whether user is the sole superadmin for the club",
            ),
        ),
    ]
