# Generated by Django 4.2.23 on 2025-07-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0044_set_default_clublogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="acronym",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="category_ids",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="date_created",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="instagram_followers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="last_updated",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="organization_guid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="organization_state",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="organization_typename",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="organization_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="supporting_institution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="alias",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
