# Generated by Django 4.2.23 on 2025-07-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0044_set_default_clublogo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["name", "-id"],
                "permissions": [("view_club_details", "Can view club details")],
            },
        ),
        migrations.RemoveField(
            model_name="clubmembership",
            name="is_admin",
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="cached_is_owner",
            field=models.BooleanField(
                blank=True,
                default=False,
                editable=False,
                help_text="Used to determine if is_owner has changed",
            ),
        ),
        migrations.AddField(
            model_name="clubrole",
            name="cached_role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("custom", "Custom"),
                ],
                default=None,
                editable=False,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clubrole",
            name="role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("custom", "Custom"),
                ],
                default="viewer",
            ),
        ),
        migrations.AddField(
            model_name="teamrole",
            name="role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("custom", "Custom"),
                ],
                default="viewer",
            ),
        ),
        migrations.AlterField(
            model_name="clubmembership",
            name="is_owner",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Determines whether user is the sole superadmin for the club",
            ),
        ),
    ]
