# Generated by Django 4.2.23 on 2025-07-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0045_remove_clubmembership_is_admin_clubrole_role_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubrole",
            name="cached_role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("custom", "Custom"),
                ],
                default="viewer",
                editable=False,
            ),
        ),
    ]
