# Generated by Django 4.2.23 on 2025-07-27 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("clubs", "0045_alter_club_options_remove_clubmembership_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="majors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Focused majors",
                related_name="clubs",
                to="core.major",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="primary_color",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[django.core.validators.RegexValidator("^#[0-9A-Fa-f]{6}$")],
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="text_color",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[django.core.validators.RegexValidator("^#[0-9A-Fa-f]{6}$")],
            ),
        ),
    ]
