# Generated by Django 4.2.23 on 2025-07-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0046_club_majors_club_primary_color_club_text_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamrole",
            options={"ordering": ["order"]},
        ),
    ]
