# Generated by Django 4.2.23 on 2025-07-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0046_clubrole_cached_role_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="cached_is_owner",
            field=models.BooleanField(
                blank=True,
                default=False,
                editable=False,
                help_text="Used to determine if is_owner has changed",
            ),
        ),
    ]
