# Generated by Django 4.2.23 on 2025-07-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0047_clubmembership_cached_is_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubrole",
            name="cached_role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("viewer", "Viewer"),
                    ("custom", "Custom"),
                ],
                default=None,
                editable=False,
                null=True,
            ),
        ),
    ]
