# Generated by Django 4.2.23 on 2025-07-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0047_alter_teamrole_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="gatorconnect_organization_guid",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="gatorconnect_organization_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="gatorconnect_organization_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="instagram_followers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="alias",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
