# Generated by Django 4.2.23 on 2025-07-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0048_club_acronym_club_category_ids_club_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="acronym",
        ),
        migrations.RemoveField(
            model_name="club",
            name="category_ids",
        ),
        migrations.RemoveField(
            model_name="club",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="club",
            name="organization_typename",
        ),
        migrations.RemoveField(
            model_name="club",
            name="supporting_institution",
        ),
        migrations.AlterField(
            model_name="club",
            name="alias",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
