# Generated by Django 4.2.23 on 2025-08-05 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0048_club_gatorconnect_organization_guid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="is_pinned",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Club is pinned on user's dashboard",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="gatorconnect_organization_url",
            field=models.TextField(
                blank=True, help_text="How they assign links to clubs", null=True
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="gatorconnect_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the gatorconnect page",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^https:\\/\\/orgs\\.studentinvolvement\\.ufl\\.edu\\/Organization\\/"
                    )
                ],
            ),
        ),
    ]
