# Generated by Django 4.2.23 on 2025-07-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0048_alter_clubrole_cached_role_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "ordering": ["name", "-id"],
                "permissions": [
                    ("view_club_details", "Can see extended information for a club")
                ],
            },
        ),
    ]
