# Generated by Django 4.2.23 on 2025-07-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0049_remove_club_acronym_remove_club_category_ids_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="date_created",
        ),
    ]
