# Generated by Django 4.2.23 on 2025-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0049_clubmembership_is_pinned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubrole",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Used to determine the list ordering of a member"
            ),
        ),
    ]
