# Generated by Django 4.2.23 on 2025-08-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0050_clubrole_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubrole",
            options={"ordering": ["order"]},
        ),
    ]
