# Generated by Django 4.2.23 on 2025-08-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0051_alter_clubrole_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="is_csu_partner",
            field=models.BooleanField(
                default=False, help_text="Is this club shown on the csu site?"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="mirror_gatorconnect",
            field=models.BooleanField(
                default=True,
                help_text="Should this club be updated based on info from gatorconnect?",
            ),
        ),
    ]
