# Generated by Django 4.2.23 on 2025-08-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0053_alter_club_options_alter_clubmembership_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubfile",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin Dashboard"),
                    ("submission", "Poll Submission"),
                ],
                default="admin",
            ),
        ),
    ]
