# Generated by Django 4.2.23 on 2025-08-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0053_alter_club_options_alter_clubmembership_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="order_override",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
