# Generated by Django 5.2.8 on 2025-11-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0054_clubfile_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="clubs", to="clubs.clubtag"),
        ),
    ]
