# Generated by Django 5.2.8 on 2026-02-10 13:47

import json
import os

from django.db import migrations, models

from clubs.defaults import INITIAL_CLUB_ROLES


def migrate_sync_club_roles(apps, schema_editor):
    """For each club, make sure the club has the default roles."""

    role_ids = []

    Club = apps.get_model("clubs", "Club")
    ClubRole = apps.get_model("clubs", "ClubRole")

    for club in Club.objects.annotate(roles_count=models.Count('roles')).filter(roles_count__lt=len(INITIAL_CLUB_ROLES)):
        for role in INITIAL_CLUB_ROLES:
            club_role = club.roles.filter(name=role["name"])

            if club_role.exists():
                club_role = club_role.first()
                club_role.role_type = role["role_type"]
                club_role.is_default = role["is_default"]
                club_role.is_executive = role["is_executive"]
                club_role.is_official = role["is_official"]
                club_role.is_voter = role["is_voter"]
                club_role.save()
            else:
                new_role = ClubRole.objects.create(
                    club=club,
                    name=role["name"],
                    role_type=role["role_type"],
                    is_default=role["is_default"],
                    is_executive=role["is_executive"],
                    is_official=role["is_official"],
                    is_voter=role["is_voter"],
                )
                role_ids.append(new_role.id)

    # Save ids to file to allow reversing
    os.makedirs("./generated", mode=755, exist_ok=True)
    with open("generated/clubs_0056_cache.json", mode="w+") as f:
        json.dump({"role_ids": role_ids}, f)


def migrate_reverse_sync_club_roles(apps, schema_editor):
    """Read ids of roles created from generated file, delete those roles."""

    role_ids = []

    try:
        with open("generated/clubs_0056_cache.json") as f:
            data = json.load(f)
            role_ids = data.get("role_ids", [])
    except Exception as e:
        print("Unable to open `generated/clubs_0056_cache.json`:", e)
        return

    ClubRole = apps.get_model("clubs", "ClubRole")
    ClubRole.objects.filter(id__in=role_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0055_alter_club_tags"),
    ]

    operations = [
        migrations.RunPython(migrate_sync_club_roles, migrate_reverse_sync_club_roles)
    ]
