# Generated by Django 5.2.8 on 2026-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0056_manual_sync_club_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamrole",
            name="cached_role_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                    ("follower", "Follower"),
                    ("custom", "Custom"),
                ],
                default=None,
                editable=False,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teamrole",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Used to determine the list ordering of a member"
            ),
        ),
    ]
