# Generated by Django 4.2.20 on 2025-03-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0023_remove_eventattendance_event_and_more"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="clubs",
            field=models.ManyToManyField(
                blank=True, through="events.EventHost", to="clubs.club"
            ),
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="other_clubs",
            field=models.ManyToManyField(blank=True, to="clubs.club"),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_events",
                to="clubs.club",
            ),
        ),
    ]
