# Generated by Django 4.2.20 on 2025-03-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_clubs_recurringevent_other_clubs_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventhost",
            name="one_primary_host_per_event",
        ),
        migrations.RenameField(
            model_name="eventhost",
            old_name="is_primary",
            new_name="primary",
        ),
        migrations.AddConstraint(
            model_name="eventhost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("primary", True)),
                fields=("event", "primary"),
                name="one_primary_host_per_event",
            ),
        ),
    ]
