# Generated by Django 4.2.20 on 2025-03-17 17:27

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0023_remove_eventattendance_event_and_more"),
        ("events", "0003_remove_eventhost_one_primary_host_per_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringevent",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Club that owns recurring template, hosts all the events from it.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_events",
                to="clubs.club",
            ),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="event_end_time",
            field=models.TimeField(
                blank=True,
                default=events.models.get_default_end_time,
                help_text="Each event will end at this time",
            ),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="event_start_time",
            field=models.TimeField(
                blank=True,
                default=events.models.get_default_start_time,
                help_text="Each event will start at this time",
            ),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="other_clubs",
            field=models.ManyToManyField(
                blank=True,
                help_text="These clubs host the events as secondary hosts.",
                to="clubs.club",
            ),
        ),
    ]
