# Generated by Django 4.2.23 on 2025-06-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_eventcancellation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventattendance",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_attendance",
                to="events.event",
            ),
        ),
    ]
