# Generated by Django 4.2.23 on 2025-06-28 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_eventattendance_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
