# Generated by Django 4.2.23 on 2025-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_end_date_event_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
