# Generated by Django 4.2.23 on 2025-07-06 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="event",
            name="end_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
