# Generated by Django 4.2.23 on 2025-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_remove_event_end_date_remove_event_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventhost",
            name="one_primary_host_per_event",
        ),
        migrations.RenameField(
            model_name="eventhost",
            old_name="primary",
            new_name="is_primary",
        ),
        migrations.AddConstraint(
            model_name="eventhost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("event", "is_primary"),
                name="one_primary_host_per_event",
            ),
        ),
    ]
