# Generated by Django 4.2.23 on 2025-07-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_remove_eventhost_one_primary_host_per_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("gbm", "GBM"),
                    ("workshop", "Workshop"),
                    ("social", "Social"),
                    ("internal_meeting", "Internal Meeting"),
                    ("speaker", "Speaker"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("gbm", "GBM"),
                    ("workshop", "Workshop"),
                    ("social", "Social"),
                    ("internal_meeting", "Internal Meeting"),
                    ("speaker", "Speaker"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
    ]
