# Generated by Django 4.2.23 on 2025-07-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_eventhost_one_primary_host_per_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhost',
            old_name='is_primary',
            new_name='primary',
        ),
    ]
