# Generated by Django 4.2.23 on 2025-07-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_event_event_type_recurringevent_event_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("name", "start_at", "end_at"),
                name="unique_event_by_name_and_time",
            ),
        ),
    ]
