# Generated by Django 4.2.23 on 2025-07-08 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_is_primary_eventhost_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhost',
            old_name='primary',
            new_name='is_primary',
        ),
    ]
