# Generated by Django 4.2.23 on 2025-07-21 00:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_event_unique_event_by_name_and_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "Monday"),
                        (1, "Tuesday"),
                        (2, "Wednesday"),
                        (3, "Thursday"),
                        (4, "Friday"),
                        (5, "Saturday"),
                        (6, "Sunday"),
                    ]
                ),
                null=True,
                size=None,
            ),
        ),
    ]
