# Generated by Django 4.2.23 on 2025-07-21 00:35

from django.db import migrations


def migrate_set_recurring_event_days(apps, schema_editor):
    """For each RecurringEvent, set the days field based on the day field."""
    RecurringEvent = apps.get_model("events", "RecurringEvent")

    for recurring_event in RecurringEvent.objects.all():
        recurring_event.days = [recurring_event.day]
        recurring_event.save(update_fields=["days"])


def migrate_reverse_set_recurring_event_days(apps, schema_editor):
    """Reverse the migration by clearing the days field."""
    RecurringEvent = apps.get_model("events", "RecurringEvent")

    for recurring_event in RecurringEvent.objects.all():
        recurring_event.days = None
        recurring_event.save(update_fields=["days"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_recurringevent_days"),
    ]

    operations = [
        migrations.RunPython(
            migrate_set_recurring_event_days, migrate_reverse_set_recurring_event_days
        )
    ]
