# Generated by Django 4.2.23 on 2025-07-21 00:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_set_recurring_event_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringevent",
            name="day",
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "Monday"),
                        (1, "Tuesday"),
                        (2, "Wednesday"),
                        (3, "Thursday"),
                        (4, "Friday"),
                        (5, "Saturday"),
                        (6, "Sunday"),
                    ]
                ),
                size=None,
            ),
        ),
    ]
