# Generated by Django 4.2.23 on 2025-07-21 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0044_set_default_clublogo"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("events", "0016_remove_recurringevent_day_alter_recurringevent_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="clubs.clubfile"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="make_public_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="make_public_task",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="clubs.clubfile"
            ),
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="days",
            field=utils.models.ArrayChoiceField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "Monday"),
                        (1, "Tuesday"),
                        (2, "Wednesday"),
                        (3, "Thursday"),
                        (4, "Friday"),
                        (5, "Saturday"),
                        (6, "Sunday"),
                    ]
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date of the last occurance of this event",
            ),
            preserve_default=False,
        ),
    ]
