# Generated by Django 4.2.23 on 2025-07-21 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_remove_recurringevent_day_alter_recurringevent_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringevent",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date of the last occurance of this event",
            ),
            preserve_default=False,
        ),
    ]
