# Generated by Django 4.2.23 on 2025-07-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_attachments_event_is_draft_event_is_public_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gbm", "GBM"),
                    ("workshop", "Workshop"),
                    ("social", "Social"),
                    ("internal_meeting", "Internal Meeting"),
                    ("speaker", "Speaker"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gbm", "GBM"),
                    ("workshop", "Workshop"),
                    ("social", "Social"),
                    ("internal_meeting", "Internal Meeting"),
                    ("speaker", "Speaker"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
    ]
