# Generated by Django 4.2.23 on 2025-07-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0044_set_default_clublogo"),
        ("events", "0017_alter_recurringevent_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="description",
            new_name="description_override",
        ),
        migrations.AddField(
            model_name="event",
            name="attachments_override",
            field=models.ManyToManyField(blank=True, to="clubs.clubfile"),
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="recurring_events", to="clubs.clubfile"
            ),
        ),
    ]
