# Generated by Django 4.2.23 on 2025-07-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_attachments_event_is_draft_event_is_public_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"permissions": [("view_private_event", "Can view private event")]},
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="last_synced",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Last time events were synced",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gbm", "GBM"),
                    ("workshop", "Workshop"),
                    ("social", "Social"),
                    ("internal_meeting", "Internal Meeting"),
                    ("speaker", "Speaker"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gbm", "GBM"),
                    ("workshop", "Workshop"),
                    ("social", "Social"),
                    ("internal_meeting", "Internal Meeting"),
                    ("speaker", "Speaker"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
    ]
