# Generated by Django 4.2.23 on 2025-07-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_event_options_recurringevent_last_synced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_poll_submission_required",
            field=models.BooleanField(default=True),
        ),
    ]
