# Generated by Django 4.2.23 on 2025-07-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_event_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="last_synced",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Last time events were synced",
                null=True,
            ),
        ),
    ]
