# Generated by Django 4.2.23 on 2025-07-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_recurringevent_last_synced"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "permissions": [("view_private_event", "View private event for club")]
            },
        ),
    ]
