# Generated by Django 4.2.23 on 2025-08-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_recurringevent_prevent_sync_past_events_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_poll_submission_required",
            field=models.BooleanField(default=True),
        ),
    ]
