# Generated by Django 4.2.23 on 2025-08-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_event_is_poll_submission_required"),
        ("events", "0019_recurringevent_prevent_sync_past_events_and_more"),
    ]

    operations = []
