# Generated by Django 4.2.23 on 2025-08-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_event_is_poll_submission_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="mark_attendance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="mark_attendance",
            field=models.BooleanField(default=True),
        ),
    ]
