# Generated by Django 4.2.23 on 2025-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_event_is_poll_submission_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="enable_attendance",
            field=models.BooleanField(
                default=True, help_text="Create poll for event and users to attend."
            ),
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="enable_attendance",
            field=models.BooleanField(
                default=True, help_text="Create poll for event and users to attend."
            ),
        ),
    ]
