# Generated by Django 4.2.23 on 2025-08-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_event_enable_attendance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_poll_submission_required",
        ),
    ]
