# Generated by Django 4.2.23 on 2025-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_remove_event_is_poll_submission_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="enable_attendance",
            field=models.BooleanField(
                default=False, help_text="Create poll for event and users to attend."
            ),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="enable_attendance",
            field=models.BooleanField(
                default=False, help_text="Create poll for event and users to attend."
            ),
        ),
    ]
