# Generated by Django 4.2.24 on 2025-09-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0054_clubfile_origin"),
        ("events", "0023_alter_event_enable_attendance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="clubs",
            field=models.ManyToManyField(
                blank=True, db_index=True, through="events.EventHost", to="clubs.club"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_draft",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
