# Generated by Django 5.2.8 on 2025-11-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_alter_event_clubs_alter_event_is_draft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="events", to="events.eventtag"),
        ),
    ]
