# Generated by Django 5.2.8 on 2025-11-13 00:32

import django.core.validators
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_alter_event_clubs_alter_event_is_draft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringevent",
            name="end_date",
            field=models.DateField(
                help_text="Date of the last occurance of this event",
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=events.models.getMaxRecurringTime
                    )
                ],
            ),
        ),
    ]
