# Generated by Django 5.2.8 on 2025-12-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_alter_event_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "permissions": [
                    ("view_private_event", "Can view private event"),
                    ("view_event_analytics", "Can view event analytics"),
                    ("view_event_details", "Can view event details"),
                ]
            },
        ),
    ]
