# Generated by Django 5.2.8 on 2025-11-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_alter_recurringevent_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="is_synced",
            field=models.BooleanField(default=False),
        ),
    ]
