# Generated by Django 5.2.8 on 2025-12-16 18:04

import django.core.validators
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="is_synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="recurringevent",
            name="end_date",
            field=models.DateField(
                help_text="Date of the last occurance of this event",
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=events.models.getMaxRecurringTime
                    )
                ],
            ),
        ),
    ]
