# Generated by Django 5.2.8 on 2026-02-12 17:19

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_recurringevent_is_synced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="timezone",
            field=models.CharField(
                default="America/New_York",
                help_text="Timezone of the events, used to determine UTC offsets regardless of standard/daylight time",
                max_length=32,
                validators=[utils.models.validate_timezone_string],
            ),
        ),
    ]
