# Generated by Django 5.2.8 on 2026-02-25 14:42

import os

from django.db import connection, migrations


def migrate_apply_event_analytics_func_sql(apps, schema_editor):
    """Apply SQL for creating event analytics function."""
    
    file_path = os.path.join(os.path.dirname(__file__), '../sql', 'event-analytics-function.sql')
    
    with open(file_path, 'r') as f:
        sql_statements = f.read()
    
    with connection.cursor() as cursor:
        cursor.execute(sql_statements)

def migrate_reverse_event_analytics_func_sql(apps, schema_editor):
    """Drop the created function."""
    
    with connection.cursor() as cursor:
        cursor.execute("DROP FUNCTION IF EXISTS get_event_analytics")


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_recurringevent_timezone"),
        ("polls", "0027_alter_poll_options_poll_allowed_club_roles_and_more"),
        ("users", "0041_remove_emailverificationcode_used_at_and_more"),
        ("clubs", "0056_manual_sync_club_roles"),
    ]

    operations = [
        migrations.RunPython(migrate_apply_event_analytics_func_sql, migrate_reverse_event_analytics_func_sql)
    ]
