# Generated by Django 5.2.8 on 2026-03-12 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_manual_create_event_analytics_func"),
        ("polls", "0029_pollbase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="polls.polltemplate",
            ),
        ),
    ]
