name: Push Docker Images
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
      - 'production'
      - 'staging'

env:
  WORKSPACE: ${{ github.base_ref }}

jobs:
  publish-images:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Build and push images
        run: |

          if [[ "$WORKSPACE" == "production" ]]; then
            tag="latest"
          else
            tag="$WORKSPACE"
          fi

          docker buildx create --use

          docker buildx build --platform=linux/amd64,linux/arm64 -t ikehunter5/club-manager:$tag -f ./Dockerfile . --push
          docker buildx build --platform=linux/amd64,linux/arm64 -t ikehunter5/club-manager-proxy:$tag ./deploy/proxy --push
