# Generated by Django 4.2.23 on 2025-07-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_choiceinput_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollTemplate",
            fields=[
                (
                    "poll_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.poll",
                    ),
                ),
                ("template_name", models.CharField()),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gbm", "GBM"),
                            ("workshop", "Workshop"),
                            ("social", "Social"),
                            ("internal_meeting", "Internal Meeting"),
                            ("speaker", "Speaker"),
                            ("other", "Other"),
                        ],
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("polls.poll",),
        ),
        migrations.AddField(
            model_name="poll",
            name="poll_type",
            field=models.CharField(
                choices=[("standard", "Standard"), ("template", "Template")],
                default="standard",
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="pollmarkup",
            name="field",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_markup",
                to="polls.pollfield",
            ),
        ),
        migrations.AlterField(
            model_name="pollquestion",
            name="field",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_question",
                to="polls.pollfield",
            ),
        ),
    ]
