# Generated by Django 4.2.23 on 2025-07-10 23:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_choiceinput_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeinput",
            name="left_label",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="rangeinput",
            name="right_label",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="pollquestion",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("choice", "Choice"),
                    ("range", "Range"),
                    ("upload", "Upload"),
                    ("number", "Number"),
                ],
                default="text",
            ),
        ),
        migrations.AlterField(
            model_name="rangeinput",
            name="max_value",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="rangeinput",
            name="unit",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name="NumberInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_value", models.FloatField(default=0.0)),
                ("max_value", models.FloatField(default=10.0)),
                ("unit", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "decimal_places",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_number_input",
                        to="polls.pollquestion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
