# Generated by Django 4.2.23 on 2025-07-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_polltemplate_poll_poll_type_alter_pollmarkup_field_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text_value", models.CharField(blank=True, null=True)),
                ("number_value", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="choiceinput",
            name="poll_choice_type",
        ),
        migrations.RenameField(
            model_name="choiceinput",
            old_name="multiple",
            new_name="is_multiple",
        ),
        migrations.RemoveField(
            model_name="choiceinput",
            name="multiple_choice_type",
        ),
        migrations.RemoveField(
            model_name="choiceinput",
            name="single_choice_type",
        ),
        migrations.RemoveField(
            model_name="pollsubmission",
            name="data",
        ),
        migrations.AddField(
            model_name="choiceinput",
            name="choice_type",
            field=models.CharField(
                choices=[("select", "Dropdown Select"), ("radio", "Input Select")],
                default="select",
            ),
        ),
        migrations.AddField(
            model_name="pollquestionanswer",
            name="options_value",
            field=models.ManyToManyField(
                blank=True, related_name="selections", to="polls.choiceinputoption"
            ),
        ),
        migrations.AddField(
            model_name="pollquestionanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="polls.pollquestion",
            ),
        ),
        migrations.AddField(
            model_name="pollquestionanswer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="polls.pollsubmission",
            ),
        ),
        migrations.AddConstraint(
            model_name="pollquestionanswer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("text_value__isnull", False), ("number_value__isnull", True)
                    ),
                    models.Q(
                        ("text_value__isnull", True), ("number_value__isnull", False)
                    ),
                    models.Q(
                        ("text_value__isnull", True), ("number_value__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="pollanswer_text_or_number_or_option_set",
                violation_error_message='Can only set one of "text", "number", or "options".',
            ),
        ),
    ]
