# Generated by Django 4.2.23 on 2025-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_pollquestionanswer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollquestionanswer",
            name="error",
            field=models.CharField(
                blank=True, help_text="Error message if input is not valid.", null=True
            ),
        ),
        migrations.AddField(
            model_name="pollsubmission",
            name="error",
            field=models.CharField(blank=True, null=True),
        ),
    ]
