# Generated by Django 4.2.23 on 2025-08-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_event_is_poll_submission_required"),
        ("polls", "0007_pollquestionanswer_error_pollsubmission_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_poll",
                to="events.event",
            ),
        ),
    ]
