# Generated by Django 4.2.23 on 2025-08-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_poll_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollquestion",
            name="custom_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("name", "Name"),
                    ("email", "Email"),
                    ("ufl_email", "UFL Email"),
                    ("major", "Major"),
                    ("minor", "Minor"),
                    ("college", "College"),
                    ("phone", "Phone"),
                    ("graduation_date", "Graduation Date"),
                    ("department", "Department"),
                ],
                null=True,
            ),
        ),
    ]
