# Generated by Django 4.2.23 on 2025-07-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_event_is_poll_submission_required"),
        ("polls", "0008_poll_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_poll",
                to="events.event",
            ),
        ),
    ]
