# Generated by Django 4.2.23 on 2025-08-12 06:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_pollquestion_custom_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="choiceinputoption",
            name="is_default",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="pollmarkup",
            name="label",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadinput",
            name="file_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddConstraint(
            model_name="choiceinputoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("input", "is_default"),
                name="unique_default_option_per_choicefield",
            ),
        ),
    ]
