# Generated by Django 4.2.23 on 2025-08-13 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("polls", "0010_choiceinputoption_is_default_pollmarkup_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="close_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="close_task",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="open_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="open_task",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("scheduled", "Scheduled"),
                    ("draft", "Draft"),
                    ("canceled", "Canceled"),
                ],
                default="draft",
            ),
        ),
        migrations.AddField(
            model_name="pollsubmission",
            name="is_complete",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="choiceinputoption",
            name="order",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="pollfield",
            name="order",
            field=models.IntegerField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="poll",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("close_at__isnull", False),
                    ("open_at__isnull", True),
                    _negated=True,
                ),
                name="poll_close_date_must_have_start_date",
            ),
        ),
    ]
