# Generated by Django 4.2.23 on 2025-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_poll_close_at_poll_close_task_poll_open_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("scheduled", "Scheduled"),
                    ("draft", "Draft"),
                ],
                default="draft",
                editable=False,
            ),
        ),
    ]
