# Generated by Django 4.2.23 on 2025-08-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0053_alter_club_options_alter_clubmembership_options_and_more"),
        ("polls", "0012_alter_poll_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={"ordering": ["-open_at"]},
        ),
        migrations.AlterModelOptions(
            name="pollsubmission",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="pollquestion",
            old_name="required",
            new_name="is_required",
        ),
        migrations.RemoveField(
            model_name="pollquestion",
            name="custom_type",
        ),
        migrations.AddField(
            model_name="poll",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="clubs.club",
            ),
        ),
        migrations.AddField(
            model_name="pollquestion",
            name="is_user_lookup",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="pollquestion",
            name="link_user_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("name", "Name"),
                    ("major", "Major"),
                    ("minor", "Minor"),
                    ("college", "College"),
                    ("phone", "Phone"),
                    ("graduation_date", "Graduation Year"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("scheduled", "Scheduled"),
                    ("draft", "Draft"),
                ],
                default="draft",
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="textinput",
            name="text_type",
            field=models.CharField(
                choices=[
                    ("short", "Short Text"),
                    ("long", "Long Text"),
                    ("rich", "Rich Text"),
                ],
                default="short",
            ),
        ),
    ]
