# Generated by Django 4.2.23 on 2025-08-16 04:47

from django.db import migrations


def migrate_assign_club_to_poll(apps, schema_editor):
    """For each poll, assign a club."""

    Poll = apps.get_model("polls", "Poll")
    Club = apps.get_model("clubs", "Club")
    default_club = Club.objects.filter(name="Computing Student Union")

    if default_club.exists():
        default_club = default_club.first()
    else:
        default_club = None

    for poll in Poll.objects.all():
        try:
            if (
                poll.event is not None
                and poll.event.hosts.filter(is_primary=True).exists()
            ):
                poll.club = poll.event.hosts.get(is_primary=True).club
            elif default_club:
                poll.club = default_club
            else:
                poll.poll_type = "template"

            poll.save()

        except Exception as e:
            print(
                f"Encountered error when assigning club to poll {poll.__str__()}:",
                e,
            )
            poll.poll_type = "template"
            poll.save()


def migrate_reverse_assign_club_to_poll(apps, schema_editor):
    """For each poll, remove club assignment."""

    Poll = apps.get_model("polls", "Poll")

    for poll in Poll.objects.all():
        poll.club = None
        poll.save()


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0013_alter_poll_options_alter_pollsubmission_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_assign_club_to_poll, migrate_reverse_assign_club_to_poll
        )
    ]
