# Generated by Django 4.2.23 on 2025-08-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0014_manual_assign_poll_club"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="poll",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("club__isnull", True), ("poll_type", "standard"), _negated=True
                ),
                name="only_poll_templates_allow_null_club",
            ),
        ),
    ]
