# Generated by Django 4.2.23 on 2025-08-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0015_poll_only_poll_templates_allow_null_club"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pollfield",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterField(
            model_name="pollquestionanswer",
            name="error",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Error message if input is not valid.",
                null=True,
            ),
        ),
    ]
