# Generated by Django 4.2.23 on 2025-08-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0016_alter_pollfield_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollquestion",
            name="link_user_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("name", "Name"),
                    ("phone", "Phone"),
                    ("major", "Major"),
                    ("minor", "Minor"),
                    ("college", "College"),
                    ("graduation_date", "Graduation Year"),
                ],
                null=True,
            ),
        ),
    ]
