# Generated by Django 4.2.23 on 2025-08-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0017_alter_pollquestion_link_user_field"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RangeInput",
            new_name="ScaleInput",
        ),
        migrations.AlterField(
            model_name="pollquestion",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("choice", "Choice"),
                    ("scale", "Scale"),
                    ("upload", "Upload"),
                    ("number", "Number"),
                ],
                default="text",
            ),
        ),
    ]
