# Generated by Django 4.2.23 on 2025-08-17 04:23

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0054_clubfile_origin"),
        ("polls", "0018_rename_rangeinput_scaleinput_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckboxInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_consent", models.BooleanField(blank=True, null=True)),
                ("allow_indeterminate", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DateInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_value", models.DateField(blank=True, null=True)),
                ("max_value", models.DateField(blank=True, null=True)),
                ("exclude_day", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_length",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("is_school_email", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhoneInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_value", models.TimeField(blank=True, null=True)),
                ("max_value", models.TimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UrlInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_length",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="choiceinput",
            options={},
        ),
        migrations.AddField(
            model_name="choiceinputoption",
            name="is_other",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="pollquestionanswer",
            name="boolean_value",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pollquestionanswer",
            name="file_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clubs.clubfile",
            ),
        ),
        migrations.AddField(
            model_name="pollquestionanswer",
            name="other_option_value",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadinput",
            name="max_file_size",
            field=models.BigIntegerField(
                blank=True, default=polls.models.UploadInput.get_default_upload_filesize
            ),
        ),
        migrations.AlterField(
            model_name="choiceinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AlterField(
            model_name="pollquestion",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("choice", "Choice"),
                    ("scale", "Scale"),
                    ("upload", "Upload"),
                    ("number", "Number"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("url", "Url"),
                    ("checkbox", "Checkbox"),
                ],
                default="text",
            ),
        ),
        migrations.AlterField(
            model_name="pollquestion",
            name="link_user_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("name", "Name"),
                    ("phone", "Phone"),
                    ("major", "Major"),
                    ("minor", "Minor"),
                    ("college", "College"),
                    ("graduation_date", "Graduation Date"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scaleinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_scale_input",
                to="polls.pollquestion",
            ),
        ),
        migrations.AlterField(
            model_name="textinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AlterField(
            model_name="uploadinput",
            name="file_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("audio/*", "Audio"),
                        ("video/*", "Video"),
                        ("image/*", "Image"),
                        (".pdf", "Pdf"),
                        (".txt", "Text"),
                        (".docx", "Word"),
                        (".csv", "Csv"),
                        (".xlsx,.xls", "Excel"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddConstraint(
            model_name="choiceinputoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_other", True)),
                fields=("input", "is_other"),
                name="one_other_option_per_choicefield",
            ),
        ),
        migrations.AddField(
            model_name="urlinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AddField(
            model_name="timeinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AddField(
            model_name="phoneinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AddField(
            model_name="emailinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AddField(
            model_name="dateinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AddField(
            model_name="checkboxinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
    ]
