# Generated by Django 4.2.23 on 2025-08-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0019_checkboxinput_dateinput_emailinput_phoneinput_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choiceinput",
            name="choice_type",
            field=models.CharField(
                choices=[("dropdown", "Dropdown Select"), ("select", "Input Select")],
                default="dropdown",
            ),
        ),
    ]
