# Generated by Django 4.2.23 on 2025-08-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0020_alter_choiceinput_choice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkboxinput",
            name="label",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="checkboxinput",
            name="is_consent",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="numberinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AlterField(
            model_name="scaleinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
        migrations.AlterField(
            model_name="uploadinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_%(class)s",
                to="polls.pollquestion",
            ),
        ),
    ]
