# Generated by Django 4.2.23 on 2025-08-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_alter_link_is_tracked"),
        ("polls", "0021_checkboxinput_label_alter_checkboxinput_is_consent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollSubmissionLink",
            fields=[
                (
                    "link_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="analytics.link",
                    ),
                ),
                (
                    "poll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_submission_link",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("analytics.link",),
        ),
    ]
