# Generated by Django 4.2.23 on 2025-08-24 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0022_pollsubmissionlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="numberinput",
            name="decimal_places",
        ),
        migrations.RemoveField(
            model_name="numberinput",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="scaleinput",
            name="min_value",
        ),
        migrations.RemoveField(
            model_name="scaleinput",
            name="step",
        ),
        migrations.RemoveField(
            model_name="scaleinput",
            name="unit",
        ),
        migrations.AlterField(
            model_name="scaleinput",
            name="initial_value",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="scaleinput",
            name="max_value",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
