# Generated by Django 5.2.7 on 2025-10-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0054_clubfile_origin"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("events", "0024_alter_event_clubs_alter_event_is_draft_and_more"),
        ("polls", "0024_remove_poll_only_poll_templates_allow_null_club_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="poll",
            name="only_poll_templates_allow_null_club",
        ),
        migrations.AddConstraint(
            model_name="poll",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("club__isnull", False), ("poll_type", "template"), _connector="OR"
                ),
                name="only_poll_templates_allow_null_club",
            ),
        ),
    ]
