# Generated by Django 5.2.8 on 2025-12-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0025_remove_poll_only_poll_templates_allow_null_club_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={
                "ordering": ["-open_at"],
                "permissions": [("view_poll_analytics", "Can view poll analytics")],
            },
        ),
    ]
