# Generated by Django 5.2.8 on 2026-01-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0055_alter_club_tags"),
        ("polls", "0026_alter_poll_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={
                "ordering": ["-open_at"],
                "permissions": [
                    ("view_poll_analytics", "Can view poll analytics"),
                    ("view_private_poll", "Can view private polls"),
                ],
            },
        ),
        migrations.AddField(
            model_name="poll",
            name="allowed_club_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="If private, then only users with one of these club roles can submit a poll.",
                related_name="+",
                to="clubs.clubrole",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="is_private",
            field=models.BooleanField(
                blank=True, default=False, help_text="Only club members can submit this poll."
            ),
        ),
    ]
