# Generated by Django 5.2.8 on 2026-03-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0027_alter_poll_options_poll_allowed_club_roles_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PollTemplate",
        ),
    ]
