# Generated by Django 5.2.8 on 2026-03-12 13:58

import django.db.models.deletion
from django.db import migrations, models


def create_pollbases(apps, schema_editor):
    Poll = apps.get_model("polls", "Poll")
    PollBase = apps.get_model("polls", "PollBase")

    db_alias = schema_editor.connection.alias

    # Create base rows for Poll
    for poll in Poll.objects.using(db_alias).all():
        base = PollBase.objects.using(db_alias).create(
            id=poll.id,
            created_at=poll.created_at,
            updated_at=poll.updated_at,
            name=poll.name,
            description=poll.description,
            is_private=poll.is_private,
            club_id=poll.club_id,
        )
        poll.id = base.id
        poll.save(update_fields=["pollbase_ptr"])


def reverse_create_pollbases(apps, schema_editor):
    Poll = apps.get_model("polls", "Poll")
    PollBase = apps.get_model("polls", "PollBase")

    db_alias = schema_editor.connection.alias

    for poll in Poll.objects.using(db_alias).all():
        try:
            base = PollBase.objects.using(db_alias).get(id=poll.id)
        except PollBase.DoesNotExist:
            continue

        poll.created_at = base.created_at
        poll.updated_at = base.updated_at
        poll.name = base.name
        poll.description = base.description
        poll.is_private = base.is_private
        poll.club_id = base.club_id

        poll.save(update_fields=[
            "created_at",
            "updated_at",
            "name",
            "description",
            "is_private",
            "club_id",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0056_manual_sync_club_roles"),
        ("polls", "0028_delete_polltemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_private",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Only club members can submit this poll.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="poll",
            name="only_poll_templates_allow_null_club",
        ),
        migrations.RunPython(create_pollbases, reverse_create_pollbases),
        migrations.RemoveField(
            model_name="poll",
            name="allowed_club_roles",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="club",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="description",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="id",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="is_private",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="name",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="poll_type",
        ),
        migrations.RemoveField(
            model_name="poll",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="PollTemplate",
            fields=[
                (
                    "pollbase_ptr",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.pollbase",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gbm", "GBM"),
                            ("workshop", "Workshop"),
                            ("social", "Social"),
                            ("internal_meeting", "Internal Meeting"),
                            ("speaker", "Speaker"),
                            ("other", "Other"),
                        ],
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("polls.pollbase",),
        ),
        migrations.AddField(
            model_name="pollbase",
            name="allowed_club_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="If private, then only users with one of these club roles can submit a poll.",
                related_name="+",
                to="clubs.clubrole",
            ),
        ),
        migrations.AddField(
            model_name="pollbase",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="clubs.club",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="pollbase_ptr",
            field=models.OneToOneField(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="polls.pollbase",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollfield",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="polls.pollbase",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="template",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="polls.polltemplate",
            ),
        ),
    ]
